services:
  mcserver:
    image: itzg/minecraft-server
    environment:
      EULA: TRUE
      VERSION: "1.20.4"
      DIFFICULTY: "normal"
      SPAWN_PROTECTION: 0
      ENABLE_WHITELIST: FALSE
      #WHITELIST_FILE: "./data/whitelist.json"
    volumes:
      - ./Server:/data

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "tcp"
      - "mcserver:25565"
    environment:
      NGROK_AUTHTOKEN: 'To be set'
    ports:
      - 4040:4040
    depends_on:
      - mcserver

  discordbot:
    build: ./DiscordBot
    environment:
      DISCORD_BOT_TOKEN: "To be set"
      NGROK_IP: "ngrok"
    depends_on:
      - mcserver
      - ngrok