services:
  mcserver:
    image: itzg/minecraft-server
    environment:
      EULA: TRUE
      VERSION: "1.20.4"
      DIFFICULTY: "normal"
      SPAWN_PROTECTION: 0
      ENABLE_WHITELIST: FALSE
      #WHITELIST_FILE: "./data/whitelist.json"
    network_mode: "host"
    volumes:
      - ./Server:/data

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "tcp"
      - "25565"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    network_mode: "host"
    depends_on:
      - mcserver

#  discordbot:
#    build: .
#    environment:
#      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}