services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
          - "tcp" #Must open something cause contaier will not work else
          - "99999"
    environment:
      NGROK_AUTHTOKEN: 'To be set'
    network_mode: "host"

  discordbot:
    build: ./DiscordBot
    restart: unless-stopped
    environment:
      DISCORD_BOT_TOKEN: "To be set"
      NGROK_IP: "localhost"
      RCON_IP: "localhost"
      RCON_PASSWORD: "RconPassword"
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Blueprints:/Blueprints
    depends_on:
      ngrok:
        condition: service_started